name: get artifactory secrets
description: Get artifactory from GSM and creates Github env variables
inputs:
  GOOGLE_PROJECT:
    description: "GSM project"
    required: true

runs:
  using: "Composite"
  steps:
    - name: "load GSM secrets"
      id: secrets
      uses: google-github-actions/get-secretmanager-secrets@v2
      with:
        secrets: |-
          artifactory_username:${{inputs.GOOGLE_PROJECT }}/JF_URL
          artifactory_password:${{inputs.GOOGLE_PROJECT }}/JF_URL
          
